name: Deploy to Cloudflare Worker (daily)

on:
  schedule:
    - cron: "0 21 * * SUN" # 毎週日本時間月曜日06:00に実行
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout target branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*
      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Fetch data
        run: pnpm run fetch:all
      - name: Build
        run: pnpm run build
      - name: Deploy with Wrangler
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          MM_USERNAME: ${{ secrets.MM_USERNAME }}
          MM_PASSWORD: ${{ secrets.MM_PASSWORD }}
      - name: Set date variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mmdash-data-${{ env.DATE }}
          path: src/lib/data
          retention-days: 0
